#!/bin/bash

DEPS=-r:/usr/lib/mono/nuget/Google.Protobuf.3.3.0/lib/net45/Google.Protobuf.dll

mcs -unsafe $DEPS -t:library -out:$1/Mtk.dll /codes/Mtk/*.cs
mcs -unsafe $DEPS -t:library -r:$1/Mtk.dll -out:$1/Server.dll /codes/Server/*.cs /codes/Server/*/*.cs /codes/Server/*/*/*.cs

